live_config_reload = true

[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Beam"

[font]
size = 10.0

# fc-list | grep -i terminus
[font.bold]
family = "xos4 Terminus"

[font.italic]
family = "xos4 Terminus"

[font.normal]
family = "xos4 Terminus"

[mouse]
hide_when_typing = true
