
[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Beam"

[font]
size = 12.0

# fc-list | grep -i terminus
# fc-list | grep -i terminess
[font.bold]
family = "Terminess Nerd Font"

[font.italic]
family = "Terminess Nerd Font"

[font.normal]
family = "Terminess Nerd Font"

[mouse]
hide_when_typing = true

[general]
live_config_reload = true
